"""
Session replay — reconstruct and re-execute API call sequences from
call records.

Useful for:
  - Debugging:  rerun calls step by step to reproduce an issue.
  - Regression: verify that the same call sequence produces consistent results.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from measure_api.logger import get_logger
from measure_api.project import MeasureProject

logger = get_logger("replay")


class SessionReplay:
    """
    Replay an API session from its trace file.

    Usage:
        replay = SessionReplay.from_trace(
            "call_records/2026-07-09/session_sess-a1b2_trace.json"
        )
        results = replay.replay_all()
        results = replay.replay_upto(seq=4)
        results = replay.replay_upto(call_id="trk-0004")
    """

    def __init__(self, trace: Dict[str, Any], record_dir: str) -> None:
        """
        Args:
            trace: Parsed session trace dict.
            record_dir: Base directory containing the call record files.
        """
        self._trace = trace
        self._record_dir = record_dir
        self._calls: List[Dict] = trace.get("calls", [])
        self._project: Optional[MeasureProject] = None
        self._results: List[Dict] = []

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def from_trace(cls, trace_path: str) -> "SessionReplay":
        """
        Load a session trace JSON file.

        Args:
            trace_path: Path to a session trace file (generated by
                        ``CallRecorder``).

        Returns:
            ``SessionReplay`` instance ready for replay.
        """
        trace_path = os.path.abspath(trace_path)
        if not os.path.isfile(trace_path):
            raise FileNotFoundError(f"Trace file not found: {trace_path}")

        with open(trace_path, "r", encoding="utf-8") as f:
            trace = json.load(f)

        record_dir = os.path.dirname(trace_path)
        return cls(trace, record_dir)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def session_id(self) -> str:
        return self._trace.get("session_id", "unknown")

    @property
    def total_calls(self) -> int:
        return len(self._calls)

    @property
    def calls(self) -> List[Dict]:
        return list(self._calls)

    # ------------------------------------------------------------------
    # Replay
    # ------------------------------------------------------------------

    def _load_call_file(self, entry: Dict) -> Optional[Dict]:
        """Load the full call record JSON from the call file."""
        fname = entry.get("file", "")
        if not fname:
            return None
        filepath = os.path.join(self._record_dir, fname)
        if not os.path.isfile(filepath):
            logger.warning("Call file not found: %s", filepath)
            return None
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            logger.error("Failed to read call file %s: %s", filepath, e)
            return None

    def _execute_call(self, call_record: Dict) -> Dict:
        """
        Execute a single API call on the project.

        Returns:
            Dict with ``call_id``, ``function``, ``seq``, ``response``,
            and ``error``.
        """
        function = call_record.get("function", "")
        request_data = call_record.get("request", {})

        result: Dict[str, Any] = {
            "call_id": call_record.get("call_id", ""),
            "function": function,
            "seq": call_record.get("seq", 0),
            "response": None,
            "error": None,
        }

        if self._project is None:
            # First call must be create_session — extract project_dir
            if function == "create_session":
                project_dir = request_data.get("project_dir", "")
                self._project = MeasureProject(project_dir)
                result["response"] = {"session_id": "replay", "status": "created"}
                return result
            else:
                result["error"] = "No project initialized (missing create_session)"
                return result

        try:
            if function == "load_reference":
                result["response"] = self._project.load_reference(
                    request_data.get("image_path", ""),
                )
            elif function == "set_template":
                result["response"] = self._project.set_template(
                    center=tuple(request_data.get("center", (0, 0))),
                    size=tuple(request_data.get("size", (0, 0))),
                    angle_deg=float(request_data.get("angle_deg", 0)),
                    preprocessor=request_data.get("preprocessor", "raw"),
                    match_score_threshold=float(
                        request_data.get("match_score_threshold", 0.5)
                    ),
                    angle_range_deg=float(request_data.get("angle_range_deg", 30)),
                    max_matches=int(request_data.get("max_matches", 0)),
                )
            elif function == "add_measurement":
                result["response"] = self._project.add_measurement(
                    request_data.get("object_type", ""),
                    request_data.get("label", ""),
                    request_data.get("params", {}),
                )
            elif function == "update_measurement":
                result["response"] = self._project.update_measurement(
                    call_record.get("request", {})
                    .get("original_label", request_data.get("label", "")),
                    request_data.get("params", {}),
                )
            elif function == "remove_measurement":
                result["response"] = self._project.remove_measurement(
                    request_data.get("label", ""),
                )
            elif function == "add_composed":
                result["response"] = self._project.add_composed(
                    request_data.get("composed_type", ""),
                    request_data.get("label", ""),
                    request_data.get("dependencies", {}),
                )
            elif function == "remove_composed":
                result["response"] = self._project.remove_composed(
                    request_data.get("label", ""),
                )
            elif function == "save_project":
                result["response"] = self._project.save()
            elif function == "load_project":
                result["response"] = self._project.load()
            elif function == "measure":
                result["response"] = self._project.measure(
                    request_data.get("inspection_image", ""),
                )
            else:
                result["error"] = f"Unsupported function: {function}"
        except Exception as e:
            result["error"] = str(e)
            logger.warning("Replay call %s (seq=%d) failed: %s",
                           function, call_record.get("seq"), e)

        return result

    def replay_all(self) -> List[Dict]:
        """
        Replay the entire call sequence.

        Returns:
            List of result dicts, one per call.
        """
        self._project = None
        self._results = []

        for entry in self._calls:
            call_record = self._load_call_file(entry)
            if call_record is None:
                continue
            result = self._execute_call(call_record)
            self._results.append(result)

        logger.info("Replay complete: %d calls, %d succeeded",
                    len(self._results),
                    sum(1 for r in self._results if r["error"] is None))
        return self._results

    def replay_upto(self, seq: Optional[int] = None,
                    call_id: Optional[str] = None) -> List[Dict]:
        """
        Replay calls up to (and including) a specific sequence number
        or call ID.

        Args:
            seq: Sequence number to stop at (inclusive).
            call_id: Call ID to stop at (inclusive).  Takes precedence
                     if both are provided.

        Returns:
            List of result dicts.
        """
        self._project = None
        self._results = []

        target_seq = seq
        if call_id is not None:
            for entry in self._calls:
                if entry.get("call_id") == call_id:
                    target_seq = entry.get("seq")
                    break
            if target_seq is None:
                raise ValueError(f"Call ID '{call_id}' not found in trace")

        for entry in self._calls:
            if entry.get("seq", 0) > (target_seq or 0):
                break
            call_record = self._load_call_file(entry)
            if call_record is None:
                continue
            result = self._execute_call(call_record)
            self._results.append(result)

        return self._results

    def replay_function(self, function_name: str) -> List[Dict]:
        """
        Replay only calls matching a specific function name.

        Note: This replays the entire context (earlier calls are needed
        to set up the project state), but only returns results for the
        matching calls.
        """
        all_results = self.replay_all()
        return [r for r in all_results if r["function"] == function_name]
